export type AttractionCategory = "monument" | "museum" | "church" | "square" | "park" | "experience";
export type WeatherType = "outdoor" | "indoor" | "both";
export type ProfileTag = "family" | "couple" | "friends";

export type Attraction = {
  id: string;
  name: string;
  neighborhood: string;
  category: AttractionCategory;
  weather: WeatherType;
  profiles: ProfileTag[];
  description: string;
  tip: string;
  duration: string;
  durationHours: number;
  cost: string;
  costEur: number;
  mustSee: boolean;
};

export const categoryLabels: Record<AttractionCategory, string> = {
  monument: "Monumentos",
  museum: "Museus",
  church: "Igrejas",
  square: "Praças & Fontes",
  park: "Parques & Bairros",
  experience: "Experiências",
};

export const categoryIcons: Record<AttractionCategory, string> = {
  monument: "🏛️",
  museum: "🖼️",
  church: "⛪",
  square: "⛲",
  park: "🌿",
  experience: "✨",
};

export const attractions: Attraction[] = [
  // MONUMENTOS
  {
    id: "colosseum",
    name: "Coliseu",
    neighborhood: "Centro Histórico",
    category: "monument",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "O maior anfiteatro romano já construído, erguido no século I d.C. para abrigar até 80 mil espectadores. Palco de combates de gladiadores e espetáculos públicos, é o símbolo máximo do Império Romano e o monumento mais visitado da Itália.",
    tip: "Reserve online com antecedência — as filas presenciais podem passar de 2 horas. O ingresso inclui o Fórum Romano e o Palatino.",
    duration: "2–3 horas",
    durationHours: 2.5,
    cost: "€18",
    costEur: 18,
    mustSee: true,
  },
  {
    id: "forum",
    name: "Fórum Romano",
    neighborhood: "Centro Histórico",
    category: "monument",
    weather: "outdoor",
    profiles: ["family", "couple", "friends"],
    description: "O coração político e social da Roma Antiga, onde senadores debatiam, comerciantes negociavam e imperadores desfilavam em triunfo. Hoje é um dos sítios arqueológicos mais fascinantes do mundo, com ruínas que remontam a séculos antes de Cristo.",
    tip: "Incluso no ingresso do Coliseu. Vá de manhã cedo para evitar o calor e a multidão. Baixe um app de realidade aumentada para 'ver' como era.",
    duration: "1–2 horas",
    durationHours: 1.5,
    cost: "Incluso no Coliseu",
    costEur: 0,
    mustSee: true,
  },
  {
    id: "palatino",
    name: "Monte Palatino",
    neighborhood: "Centro Histórico",
    category: "monument",
    weather: "outdoor",
    profiles: ["couple", "friends"],
    description: "Uma das sete colinas de Roma e o lugar onde, segundo a lenda, Rômulo fundou a cidade. Aqui ficavam os palácios dos imperadores, com vistas panorâmicas sobre o Fórum Romano e o Circo Máximo.",
    tip: "Incluso no ingresso do Coliseu. Menos visitado que o Fórum, mas as vistas de cima valem muito — leve água.",
    duration: "1 hora",
    durationHours: 1,
    cost: "Incluso no Coliseu",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "pantheon",
    name: "Pantheon",
    neighborhood: "Centro Histórico",
    category: "monument",
    weather: "indoor",
    profiles: ["family", "couple", "friends"],
    description: "Construído em 125 d.C. pelo imperador Adriano, o Pantheon é o edifício da Antiguidade melhor preservado do mundo. Sua cúpula de concreto romano, com o famoso óculo aberto ao céu, continua sendo uma das maiores maravilhas da engenharia humana.",
    tip: "Agora cobra ingresso (€5). Chegue cedo ou no final da tarde para evitar filas. O interior é espetacular em dias de chuva — a água cai pelo óculo e escoa pelo piso.",
    duration: "30–45 min",
    durationHours: 0.75,
    cost: "€5",
    costEur: 5,
    mustSee: true,
  },
  {
    id: "castel-angelo",
    name: "Castel Sant'Angelo",
    neighborhood: "Prati / Vaticano",
    category: "monument",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "Construído como mausoléu do imperador Adriano no século II, o castelo foi fortaleza, prisão e residência papal ao longo dos séculos. Do terraço, a vista sobre o Tibre e São Pedro é uma das mais bonitas de Roma.",
    tip: "O museu interno tem belas coleções de armamentos e arte. A vista do terraço ao entardecer é romântica e espetacular. 👨‍👩‍👧 As crianças adoram a temática de castelo e cavaleiros.",
    duration: "1,5–2 horas",
    durationHours: 1.75,
    cost: "€15",
    costEur: 15,
    mustSee: true,
  },
  {
    id: "arco-constantino",
    name: "Arco de Constantino",
    neighborhood: "Centro Histórico",
    category: "monument",
    weather: "outdoor",
    profiles: ["family", "couple", "friends"],
    description: "Erguido em 315 d.C. para celebrar a vitória de Constantino, é o maior arco triunfal de Roma e um dos mais bem preservados da Antiguidade. Fica ao lado do Coliseu, tornando a visita obrigatória.",
    tip: "Não tem ingresso e fica do lado de fora do Coliseu — aproveite para fotografar sem pressa.",
    duration: "15–20 min",
    durationHours: 0.25,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "circo-massimo",
    name: "Circo Máximo",
    neighborhood: "Aventino",
    category: "monument",
    weather: "outdoor",
    profiles: ["family", "friends"],
    description: "O maior estádio da Antiguidade, com capacidade para 250 mil espectadores. Era o palco das famosas corridas de bigas. Hoje é um grande parque arqueológico onde os romanos fazem piquenique e caminhadas — uma experiência autêntica.",
    tip: "Gratuito e ótimo para uma pausa entre visitas. 👨‍👩‍👧 As crianças adoram correr no espaço enorme imaginando as corridas de bigas.",
    duration: "30 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "via-appia",
    name: "Via Appia Antica",
    neighborhood: "Appia Antica",
    category: "monument",
    weather: "outdoor",
    profiles: ["couple", "friends"],
    description: "A 'rainha das estradas' romanas, construída em 312 a.C., ainda conserva grandes trechos do calçamento original. Flanqueada por mausoléus, pinheiros e campos, é uma das experiências mais evocativas de Roma — como voltar 2.000 anos no tempo.",
    tip: "Alugue uma bicicleta para percorrer a estrada — muito mais divertido e rápido. Domingos são melhores (fechada a carros). Combine com as Catacumbas.",
    duration: "2–3 horas",
    durationHours: 2.5,
    cost: "Gratuito (bicicleta ~€10)",
    costEur: 10,
    mustSee: false,
  },

  // MUSEUS
  {
    id: "museus-vaticano",
    name: "Museus do Vaticano & Capela Sistina",
    neighborhood: "Vaticano",
    category: "museum",
    weather: "indoor",
    profiles: ["family", "couple", "friends"],
    description: "Um dos maiores complexos museológicos do mundo, com mais de 70.000 obras acumuladas pelos papas ao longo de séculos. O ponto alto é a Capela Sistina, com o teto pintado por Michelangelo entre 1508 e 1512 — uma das maiores obras de arte da humanidade.",
    tip: "Reserve com meses de antecedência — as filas sem reserva podem ser de 4+ horas. O tour noturno, disponível em alguns períodos, é espetacular e menos cheio. 💑 Reserve o tour privado para uma experiência inesquecível.",
    duration: "3–4 horas",
    durationHours: 3.5,
    cost: "€17–27",
    costEur: 20,
    mustSee: true,
  },
  {
    id: "galleria-borghese",
    name: "Galleria Borghese",
    neighborhood: "Villa Borghese",
    category: "museum",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "Considerada a 'rainha das galerias privadas', abriga o maior acervo de esculturas de Bernini e algumas das pinturas mais importantes de Caravaggio. O palacete em estilo barroco, dentro dos jardins de Villa Borghese, já é uma obra de arte por si só.",
    tip: "Entrada apenas com reserva antecipada obrigatória — máximo 360 pessoas por sessão de 2 horas. Reserve com semanas de antecedência. 💑 Uma das experiências mais refinadas e românticas de Roma.",
    duration: "2 horas (sessão fixa)",
    durationHours: 2,
    cost: "€15",
    costEur: 15,
    mustSee: true,
  },
  {
    id: "musei-capitolini",
    name: "Musei Capitolini",
    neighborhood: "Capitolino",
    category: "museum",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "Os museus mais antigos do mundo, fundados em 1471 pelo Papa Sisto IV. A coleção inclui a famosa loba capitolina, a estátua equestre de Marco Aurélio e obras-primas de escultura romana. A vista da Piazza del Campidoglio, projetada por Michelangelo, é deslumbrante.",
    tip: "Menos visitado que os Museus do Vaticano, mas com acervo igualmente impressionante — e filas menores. O bilhete conjunto com o Palazzo Caffarelli vale a pena.",
    duration: "2–3 horas",
    durationHours: 2.5,
    cost: "€15",
    costEur: 15,
    mustSee: false,
  },
  {
    id: "centrale-montemartini",
    name: "Centrale Montemartini",
    neighborhood: "Ostiense",
    category: "museum",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "Um dos museus mais surpreendentes de Roma: esculturas gregas e romanas extraordinárias expostas dentro de uma usina elétrica industrial dos anos 1930. O contraste entre o mármore antigo e as máquinas de ferro é visualmente fascinante.",
    tip: "Joía escondida que a maioria dos turistas não visita. Perfeito para escapar das multidões. Fica longe do centro — vá de metrô (linha B, estação Garbatella).",
    duration: "1,5–2 horas",
    durationHours: 1.75,
    cost: "€8",
    costEur: 8,
    mustSee: false,
  },
  {
    id: "museo-nazionale-romano",
    name: "Museo Nazionale Romano",
    neighborhood: "Termini",
    category: "museum",
    weather: "indoor",
    profiles: ["friends"],
    description: "Distribuído em quatro sedes pela cidade, reúne uma das maiores coleções de arte romana do mundo, incluindo afrescos, mosaicos e esculturas da época imperial. A sede de Palazzo Massimo é a mais impressionante.",
    tip: "A sede de Palazzo Massimo (perto da Termini) tem os afrescos da Villa di Livia — entre os mais bem preservados do mundo romano. Pouco visitada, sem filas.",
    duration: "1,5–2 horas",
    durationHours: 1.75,
    cost: "€10",
    costEur: 10,
    mustSee: false,
  },

  // IGREJAS
  {
    id: "sao-pedro",
    name: "Basílica de São Pedro",
    neighborhood: "Vaticano",
    category: "church",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "A maior basílica do mundo cristão, erguida sobre o túmulo do apóstolo Pedro. Com obras de Michelangelo (a Pietà e a cúpula), Bernini (o baldaquino e a colunata) e Rafael, é um dos maiores conjuntos artísticos da humanidade.",
    tip: "A entrada na basílica é gratuita. Subir a cúpula custa €8 (a pé) ou €10 (de elevador parcial). Dress code obrigatório: ombros e joelhos cobertos. Chegue cedo para evitar filas. 👨‍👩‍👧 As crianças ficam impressionadas com a escala gigantesca.",
    duration: "1,5–2 horas",
    durationHours: 2,
    cost: "Gratuito (cúpula €8–10)",
    costEur: 9,
    mustSee: true,
  },
  {
    id: "san-giovanni",
    name: "San Giovanni in Laterano",
    neighborhood: "Laterano",
    category: "church",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "A catedral oficial do Papa e a mais antiga basílica cristã de Roma, fundada pelo imperador Constantino no século IV. O interior barroco imponente abriga estátuas dos apóstolos de Borromini e uma fachada do século XVIII que domina a piazza.",
    tip: "Muito menos visitada que São Pedro, mas historicamente ainda mais importante. Sem filas, sem multidões — uma experiência muito mais tranquila.",
    duration: "45 min",
    durationHours: 0.75,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "santa-maria-maggiore",
    name: "Santa Maria Maggiore",
    neighborhood: "Esquilino",
    category: "church",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "Uma das quatro basílicas papais de Roma, com mosaicos do século V entre os mais antigos e bem preservados do mundo ocidental. O campanário é o mais alto de Roma.",
    tip: "Gratuita e muito tranquila. Os mosaicos do século V na abside são absolutamente deslumbrantes — leve binóculos para ver os detalhes.",
    duration: "30–45 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "san-clemente",
    name: "San Clemente al Laterano",
    neighborhood: "Laterano",
    category: "church",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "Uma das visitas mais fascinantes de Roma: três camadas de história sobrepostas. A basílica medieval do século XII fica sobre uma basílica paleocristã do século IV, que por sua vez fica sobre um templo de Mitra do século I d.C. É literalmente uma viagem no tempo.",
    tip: "Joia escondida — poucos turistas chegam aqui. A descida às camadas inferiores custa €10 e vale cada centavo. Perfeito para quem ama história.",
    duration: "1 hora",
    durationHours: 1,
    cost: "€10",
    costEur: 10,
    mustSee: false,
  },
  {
    id: "san-luigi",
    name: "San Luigi dei Francesi",
    neighborhood: "Centro Histórico",
    category: "church",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "Uma igreja aparentemente comum que esconde um dos maiores tesouros artísticos de Roma: três pinturas monumentais de Caravaggio na Cappella Contarelli, incluindo 'A Vocação de São Mateus' — considerada uma das obras de arte mais importantes do mundo.",
    tip: "Gratuita e a dois minutos da Piazza Navona. Leve moedas de €0,50 para iluminar os Caravaggios. Chegue quando abre (manhã) — fica vazia.",
    duration: "20–30 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "santa-maria-trastevere",
    name: "Santa Maria in Trastevere",
    neighborhood: "Trastevere",
    category: "church",
    weather: "indoor",
    profiles: ["couple", "friends"],
    description: "Considerada a primeira igreja dedicada à Virgem Maria em Roma, fundada no século III. A basílica atual, do século XII, tem mosaicos dourados byzantinos extraordinários na abside e uma atmosfera medieval que poucas igrejas de Roma preservam.",
    tip: "Fica no coração de Trastevere — combine a visita com um jantar no bairro. A praça em frente é perfeita para sentar e observar a vida local. 💑 Muito romântica ao entardecer.",
    duration: "30 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },

  // PRAÇAS & FONTES
  {
    id: "fontana-trevi",
    name: "Fontana di Trevi",
    neighborhood: "Centro Histórico",
    category: "square",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "A maior e mais famosa fonte barroca do mundo, esculpida por Nicola Salvi no século XVIII. A tradição de jogar uma moeda para garantir o retorno a Roma é conhecida mundialmente. Mais de €1 milhão em moedas é recolhido por ano e doado para a caridade.",
    tip: "Vá de madrugada (entre 2h e 5h da manhã) para encontrá-la quase vazia e iluminada — uma experiência completamente diferente. 💑 Inesquecível à noite. 👨‍👩‍👧 As crianças adoram a tradição da moeda.",
    duration: "30–45 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: true,
  },
  {
    id: "piazza-navona",
    name: "Piazza Navona",
    neighborhood: "Centro Histórico",
    category: "square",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "A mais bela praça barroca de Roma, construída sobre o estádio do imperador Domiciano. Tem três fontes, sendo a Fontana dei Quattro Fiumi de Bernini a mais famosa. É o centro da vida social do centro histórico, com cafés, artistas de rua e animação o dia todo.",
    tip: "Evite os restaurantes com mesa na praça — são caros e medíocres. Coma nas ruas laterais. 👨‍👩‍👧 Perfeito para crianças pela animação e espaço. No Natal vira um mercado temático muito bonito.",
    duration: "30–60 min",
    durationHours: 0.75,
    cost: "Gratuito",
    costEur: 0,
    mustSee: true,
  },
  {
    id: "piazza-spagna",
    name: "Piazza di Spagna & Escadaria",
    neighborhood: "Centro Histórico",
    category: "square",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "A Escadaria de Trinità dei Monti, com seus 135 degraus, é um dos símbolos mais icônicos de Roma. Na base fica a Fontana della Barcaccia, de Bernini. A praça é o ponto de encontro dos elegantes e o início da Via Condotti, a rua das grifes.",
    tip: "Proibido sentar nos degraus (multa de €250). Suba a escadaria até o topo para uma bela vista da praça. Primavera: os degraus ficam cobertos de azaleias cor-de-rosa. 👨‍👩‍👧 As crianças adoram subir correndo.",
    duration: "30 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: true,
  },
  {
    id: "piazza-popolo",
    name: "Piazza del Popolo",
    neighborhood: "Flaminio",
    category: "square",
    weather: "outdoor",
    profiles: ["family", "couple", "friends"],
    description: "Uma das maiores e mais imponentes praças de Roma, com um obelisco egípcio no centro e duas igrejas barrocas idênticas a guardar a entrada das três principais ruas do centro histórico. Durante séculos foi o ponto de chegada de viajantes vindos do norte.",
    tip: "Suba à Terrazza del Pincio (de graça) para a melhor vista panorâmica de Roma ao pôr do sol. Praticamente sem turistas nesse mirante.",
    duration: "30–45 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "campo-fiori",
    name: "Campo de' Fiori",
    neighborhood: "Centro Histórico",
    category: "square",
    weather: "outdoor",
    profiles: ["couple", "friends"],
    description: "A praça mais animada e popular de Roma, famosa pelo mercado matinal de frutas e verduras que funciona há séculos. À noite transforma-se num dos pontos de encontro favoritos dos jovens romanos e turistas, com dezenas de bares ao ar livre.",
    tip: "Vá de manhã cedo para o mercado — uma das experiências mais autênticas de Roma. À noite a praça fica muito movimentada. 👫 Perfeito para grupos de amigos.",
    duration: "30–60 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "piazza-venezia",
    name: "Piazza Venezia & Altare della Patria",
    neighborhood: "Centro Histórico",
    category: "square",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "O Altare della Patria (ou Vittoriano), monumento imponente em mármore branco erguido em 1911 para homenagear Vítor Emanuel II, domina a praça. Os romanos o chamam carinhosamente de 'máquina de escrever'. O terraço panorâmico no topo é gratuito.",
    tip: "O elevador até o terraço supremo custa €7 e oferece a melhor vista 360° de Roma — mais fácil e acessível que subir a cúpula de São Pedro. 👨‍👩‍👧 Ótimo para a família pela vista impressionante.",
    duration: "30–60 min",
    durationHours: 0.75,
    cost: "Gratuito (terraço €7)",
    costEur: 7,
    mustSee: false,
  },

  // PARQUES & BAIRROS
  {
    id: "villa-borghese",
    name: "Villa Borghese",
    neighborhood: "Villa Borghese",
    category: "park",
    weather: "outdoor",
    profiles: ["family", "couple", "friends"],
    description: "O maior parque público de Roma, com 80 hectares de jardins, fontes, lagos e monumentos. Além da Galleria Borghese, abriga um zoológico, museus, cinemas ao ar livre e o terraço do Pincio com vista panorâmica da cidade.",
    tip: "Alugue barquinhos no lago ou bicicletas para explorar. 👨‍👩‍👧 Perfeito para famílias com crianças — muito espaço, zoológico e parque de diversões próximos. 💑 Piquenique no jardim ao entardecer é muito romântico.",
    duration: "2–4 horas",
    durationHours: 3,
    cost: "Gratuito (atividades à parte)",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "trastevere",
    name: "Trastevere",
    neighborhood: "Trastevere",
    category: "park",
    weather: "both",
    profiles: ["couple", "friends"],
    description: "O bairro mais charmos e autêntico de Roma, com ruelas de pedra, heras nas fachadas medievais, roupas estendidas entre os prédios e o melhor ambiente noturno da cidade. É o Roma que os romanos amam — longe dos roteiros turísticos convencionais.",
    tip: "Passe pelo menos uma noite aqui para jantar e beber vinho nas ruelas. 💑 Um dos ambientes mais românticos da Europa. Visite de manhã para ver o bairro acordar sem turistas.",
    duration: "2–3 horas",
    durationHours: 2.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: true,
  },
  {
    id: "prati",
    name: "Prati",
    neighborhood: "Prati",
    category: "park",
    weather: "both",
    profiles: ["family", "couple", "friends"],
    description: "O bairro elegante e residencial próximo ao Vaticano, com grandes boulevards, lojas de qualidade e alguns dos melhores restaurantes e gelaterie de Roma. É onde muitos romanos fazem as suas compras do dia a dia — autêntico e sem multidões.",
    tip: "Base excelente para se hospedar — bem localizado, tranquilo e com bons preços. A Via Cola di Rienzo é a principal rua de compras. 👨‍👩‍👧 Tranquilo e seguro para famílias.",
    duration: "1–2 horas",
    durationHours: 1.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "coppede",
    name: "Quartiere Coppedè",
    neighborhood: "Trieste",
    category: "park",
    weather: "outdoor",
    profiles: ["couple", "friends"],
    description: "Um bairro absolutamente fora do comum, projetado pelo arquiteto Gino Coppedè entre 1913 e 1926 num estilo que mistura art nouveau, Liberty, gótico e fantástico. As fachadas decoradas com carrancas, mosaicos e arabescos parecem saídas de um conto de fadas.",
    tip: "Joia escondida que 95% dos turistas nunca veem. Fica a 20 minutos do centro de táxi. Perfeito para fotografias únicas. 💑 Muito instagramável e romântico.",
    duration: "45–60 min",
    durationHours: 0.75,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },

  // EXPERIÊNCIAS ÚNICAS
  {
    id: "buraco-fechadura",
    name: "Buraco de Fechadura dos Cavaleiros de Malta",
    neighborhood: "Aventino",
    category: "experience",
    weather: "outdoor",
    profiles: ["couple", "friends"],
    description: "No topo do Aventino, a sede da Ordem de Malta tem um portão com um buraco de fechadura que enquadra perfeitamente a cúpula de São Pedro ao fundo de um longo jardim — criando uma das perspectivas mais surpreendentes e mágicas de toda Roma.",
    tip: "Chega sempre uma fila pequena, mas vale esperar os 2 minutos. Combine com uma visita ao Roseto Comunale (jardim de rosas gratuito ao lado) e ao Jardim dos Laranjos com vista para Roma.",
    duration: "30 min",
    durationHours: 0.5,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
  {
    id: "catacumbas",
    name: "Catacumbas di Domitilla",
    neighborhood: "Appia Antica",
    category: "experience",
    weather: "indoor",
    profiles: ["family", "couple", "friends"],
    description: "As maiores e mais bem preservadas catacumbas de Roma, com mais de 17 km de galerias subterrâneas e afrescos do século II. Sepulturas de mais de 150 mil cristãos dos primeiros séculos do Cristianismo — uma experiência histórica e espiritual única.",
    tip: "Temperatura constante de 15°C nas galerias — leve uma camada extra mesmo no verão. 👨‍👩‍👧 Crianças maiores de 7 anos costumam achar fascinante, mas o ambiente pode assustar os menores. Combine com a Via Appia.",
    duration: "1–1,5 horas",
    durationHours: 1.25,
    cost: "€10",
    costEur: 10,
    mustSee: false,
  },
  {
    id: "parco-acquedotti",
    name: "Parco degli Acquedotti",
    neighborhood: "Appia Antica",
    category: "experience",
    weather: "outdoor",
    profiles: ["couple", "friends"],
    description: "Um parque arqueológico extraordinário onde aquedutos romanos de 2.000 anos cruzam campos abertos onde os romanos passeiam com cachorros e fazem piquenique. Uma das experiências mais autênticas e pouco turísticas de Roma — a cidade dos locais.",
    tip: "Quase nenhum turista vai aqui. Leve comida e vinho e faça um piquenique sob os aquedutos. 💑 Romântico e completamente diferente do circuito turístico. De metrô: linha A até Cinecittà.",
    duration: "1,5–2 horas",
    durationHours: 1.75,
    cost: "Gratuito",
    costEur: 0,
    mustSee: false,
  },
];
